project:
  type: website
  output-dir: docs

website:
  title: "Veronica De Leon"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - sidebar:dataviz
      
  sidebar:
    - id: dataviz
      title: "Data Viz"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - dataviz.qmd
        - tidytues1.qmd
        - tidytues2.qmd
        - miniproj_2.qmd

format:
  html:
    theme: 
      light: Sandstone
      dark: Lux
    css: styles.css
    toc: true

editor: visual


