---
title: "miniproj_2"
---

```{r}
library(tidyverse)
library(ggplot2)
library(stringr)
```

```{r}
netflix <- read.csv("../veronica-2222.github.io/netflix_titles.csv")
```

```{r}
# Which Comedy TV shows were added on netflix on 2021
shows <- netflix |>
  select(type, duration, title, date_added, listed_in) |>
  group_by(type) |>
  filter(str_detect(type, "TV Show")) |>
  filter(str_detect(date_added , "2021")) |>
  filter(str_detect(listed_in, "Comedies")) |>
  mutate(season = str_sub(duration, 1, 1)) |> 
  summarize(type, title, season)

shows
```

```{r}
shows |>
  ggplot(aes(y = season)) +
  geom_bar()
```

```{r}
#International Shows/Movies
international <- netflix |>
  select(type, title, country, listed_in) |>
  group_by(country) |>
  filter(str_detect(listed_in, "International")) |>
  summarize(type, title, country, listed_in) 

international
```

```{r}
international_over_fifty <- international |>
  select(title, type, country, listed_in) |>
  group_by(country) |>
  summarize(count = n()) |>
  filter(count >= 50) |>
  arrange(desc(count))

international_over_fifty 
```

```{r}
international_over_fifty <- international |>
  select(title, type, country, listed_in) |>
  group_by(country) |>
  mutate(count = n()) |>
  filter(count >= 50) |>
  arrange(desc(count))

international_over_fifty |>
  ggplot(aes(y = fct_reorder(country, count))) +
  geom_bar()
```

```{r}
# Release year vs date added on Netflix
netflix |>
  select(release_year, date_added) |>
  mutate(added_year = str_extract(date_added, "(?<=, ).+(?=$)")) |>
  ggplot(aes(x = release_year, y = added_year)) +
  geom_point()
```

\

```{r}
# table of Titles and type together in one string of movies/tv shows added on netflix on christmas eve

  netflix |>
  select(title, type, date_added) |>
  mutate(movieinfo =  str_c(title, type, sep=': ')) |>
  mutate(first_date = str_extract(date_added, ".+(?=,)")) |>
    filter(first_date == "December 24") |>
    select(movieinfo, first_date)
 
```

```{r}
# rating vs. listed_in (but only take first category it's listed in) -- need to use regular expression to only get the thing after TV- and to only get first category in listed in

netflix|>
  select(rating, listed_in) |>
  mutate(tv_rating = str_extract(rating, "(?<=-).+(?=$)")) |>
  mutate(first_listed = str_extract(listed_in, "\\w+")) |>
  filter(first_listed %in% c("Action", "Crime", "Dramas", "Comedies")) |>
  ggplot(aes(x = tv_rating, color = first_listed)) +
  geom_bar() 

#groupby count of tv_ratings
#filter action, comedies, crime, dramas

```
